using System;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using TAMHR.ESS.Domain;
using TAMHR.ESS.Infrastructure.Helpers;
using Agit.Common;
using Agit.Domain;
using Agit.Common.Utility;
using Agit.Domain.UnitOfWork;
using FluentFTP;
using PdfSharp.Pdf;
using PdfSharp.Pdf.IO;

namespace TAMHR.ESS.Infrastructure.DomainServices
{
    /// <summary>
    /// Service class that handle SPT.
    /// </summary>
    public class SptService : DomainServiceBase
    {
        #region Variables & Properties
        /// <summary>
        /// Config service object.
        /// </summary>
        private readonly ConfigService _configService;

        /// <summary>
        /// Personal data service object.
        /// </summary>
        private readonly PersonalDataService _personalDataService;
        #endregion

        #region Constructor
        /// <summary>
        /// Public constructor.
        /// </summary>
        /// <param name="configService">This <see cref="ConfigService"/> object.</param>
        /// <param name="personalDataService">This <see cref="PersonalDataService"/> object.</param>
        /// <param name="unitOfWork">This <see cref="IUnitOfWork"/> concrete object.</param>
        public SptService(ConfigService configService, PersonalDataService personalDataService, IUnitOfWork unitOfWork)
            : base(unitOfWork)
        {
            // Get config service object from DI container.
            _configService = configService;

            // Get personal data service object from DI container.
            _personalDataService = personalDataService;
        }
        #endregion

        public async Task<byte[]> Download(string noreg, int period, bool viewOnly = true)
        {
            // Get and set hash key.
            var key = noreg;

            // Create hash set repository object.
            var hashSet = UnitOfWork.GetRepository<UserHash>();

            // Create new parameters.
            var parameters = new Dictionary<string, object>
            {
                // Get and set noreg.
                ["noreg"] = noreg,
                // Get and set period (in years).
                ["period"] = period,
                // Get and set period (synonim in years).
                ["year"] = period,
            };

            // Get and set SPT path (either file path or ftp path) from configuration with given parameters.
            var sptPath = StringHelper.Format(_configService.GetConfigValue<string>(Configurations.SptPath), parameters);

            // Get and set use ftp indicator from configuration with false as default value.
            var useFtp = _configService.GetConfigValue(Configurations.SptUseFtp, defaultValue: false);

            // Get and set default SPT password file from configuration
            // (default password to open the pdf document from file path or ftp path generated by SAP) with given parameters.
            var defaultSptPasswordFile = StringHelper.Format(_configService.GetConfigValue(Configurations.SptPasswordFile, string.Empty), parameters);

            // Get and set default owner password file from configuration (owner password is used to prevent modify the PDF document).
            var defaultOwnerPassword = _configService.GetConfigValue(Configurations.SptOwnerPassword, "Transformer6hap");

            // Get user hash by noreg and type code.
            var userHash = hashSet.Fetch()
                .AsNoTracking()
                .FirstOrDefault(x => x.NoReg == noreg && x.TypeCode == HashType.Payslip);

            // Create temporary variable to store user password.
            var password = string.Empty;

            // If user hash object is not null then update the password with decrypted user hash value.
            if (userHash != null)
            {
                // Get and set password from decrypted user hash value.
                password = Cryptography.DecryptWithHash(key, userHash.HashValue);
            }
            // Else get from the default user password from configuration.
            else
            {
                // Get personal data common attribute by noreg.
                var personalDataCommonAttribute = _personalDataService.GetPersonalDataAttribute(noreg);

                // Create new parameters.
                var defaultParameters = new Dictionary<string, object>
                {
                    // Get and set noreg.
                    ["noreg"] = noreg,
                    // Get and set NIK.
                    ["nik"] = personalDataCommonAttribute != null
                        ? (string.IsNullOrEmpty(personalDataCommonAttribute.Nik) ? noreg
                        : personalDataCommonAttribute.Nik) : noreg
                };

                // Get default user hash from configuration with given parameters.
                password = StringHelper.Format(_configService.GetConfigValue(Configurations.SptDefaultPassword, string.Empty), defaultParameters);
            }

            // Get and set filename from configuration with given parameters.
            var fileName = StringHelper.Format(_configService.GetConfigValue<string>(Configurations.SptFilename), parameters);
            
            // Create array of bytes with null as default parameter.
            byte[] bytes = null;

            // If use ftp was enabled then get the PDF file from FTP server.
            if (useFtp)
            {
                // Get and set enable ssl flag from configuration with false as default value.
                var enableSsl = _configService.GetConfigValue(Configurations.SptFtpEnableSsl, defaultValue: false);

                // Get and set ftp username from configuration.
                var ftpUsername = _configService.GetConfigValue<string>(Configurations.SptFtpUsername);

                // Get and set ftp password from configuration.
                var ftpPassword = _configService.GetConfigValue<string>(Configurations.SptFtpPassword);

                // Create URI (Uniform Resource Identifier) from SPT path.
                var uri = new Uri(sptPath);

                // Get and set host information from URI.
                var host = uri.Host;

                // Get and set port information from URI.
                var port = uri.Port;

                // Get and set local path information from URI.
                var localPath = uri.LocalPath;

                // Create FTP client with given username and password.
                var client = new FtpClient(host, port, ftpUsername, ftpPassword);

                // Connect to FTP server.
                await client.ConnectAsync();

                // Set default selected files to current file name.
                var selectedFiles = new[] { localPath + "/" + fileName.Trim(new[] { '\\', '/' }) };

                // Throw an exception if there are no files.
                Assert.ThrowIf(selectedFiles.Length == 0, "SPT for this period was not found.");

                // Determine whether using password for opening PDF document from FTP server or not.
                var usePassword = !string.IsNullOrEmpty(defaultSptPasswordFile);

                // Create master pdf document object.
                using (var masterDocument = new PdfDocument())
                {
                    // Enumerate all files from filtered files.
                    foreach (var file in selectedFiles)
                    {
                        // Create new memory stream object to store the file.
                        using (var memoryStream = new MemoryStream())
                        {
                            // Download the file from FTP server and store it into memory stream.
                            client.Download(memoryStream, file);

                            // Import PDF document from memory stream with given password if any.
                            using (var doc = usePassword ? PdfReader.Open(memoryStream, defaultSptPasswordFile, PdfDocumentOpenMode.Import) : PdfReader.Open(memoryStream, PdfDocumentOpenMode.Import))
                            {
                                // Enumerate all pages from PDF document.
                                for (var i = 0; i < doc.PageCount; i++)
                                {
                                    // Get and set PDF document page.
                                    var page = doc.Pages[i];

                                    // Add the page into master PDF document.
                                    masterDocument.AddPage(page);
                                }
                            }
                        }
                    }

                    // Disconnect from FTP server.
                    await client.DisconnectAsync();

                    // If download mode then attach the security setting for master PDF document.
                    if (!viewOnly)
                    {
                        // Attach security setting for master PDF document.
                        AttachSecuritySetting(masterDocument, password, defaultOwnerPassword);
                    }

                    // Create new memory stream object.
                    using (var memoryStream = new MemoryStream())
                    {
                        // Save the master PDF document into memory stream.
                        masterDocument.Save(memoryStream);

                        // Get and set byte array from memory stream object.
                        bytes = memoryStream.ToArray();
                    }
                }
            }
            else
            {
                // Get and set file path from given SPT path and file name.
                var filePath = Path.Combine(sptPath, fileName);

                // Throw an exception if PDF file was not found.
                Assert.ThrowIf(!File.Exists(filePath), "SPT for this period was not found.");

                // Open an existing PDF file for reading.
                using (var file = File.OpenRead(filePath))
                // Create memory stream object.
                using (var ms = new MemoryStream())
                // Open existing PDF document from file stream object with defualt SPT password and mark as modify.
                using (var doc = PdfReader.Open(file, defaultSptPasswordFile, PdfDocumentOpenMode.Modify))
                {
                    // If download mode then attach the security setting for this document.
                    if (!viewOnly)
                    {
                        // Attach the security setting for this document.
                        AttachSecuritySetting(doc, password, defaultOwnerPassword);
                    }

                    // Save the pdf document into memory stream.
                    doc.Save(ms);

                    // Get and set byte array from memory stream object.
                    bytes = ms.ToArray();
                }
            }

            // Return the modify PDF document in byte array.
            return bytes;
        }

        /// <summary>
        /// Attach security setting for given pdf document.
        /// </summary>
        /// <param name="pdfDocument">This <see cref="PdfDocument"/> object.</param>
        /// <param name="password">This user password.</param>
        /// <param name="defaultOwnerPassword">This default owner password.</param>
        private void AttachSecuritySetting(PdfDocument pdfDocument, string password, string defaultOwnerPassword)
        {
            // Get and set enable printing indicator from configuration.
            var enablePrinting = _configService.GetConfigValue(Configurations.SptEnablePrinting, defaultValue: false);

            // Get and set enable document editing indicator from configuration.
            var enableEditing = _configService.GetConfigValue(Configurations.SptEnableEditing, defaultValue: false);

            // Get and set security settings object from given pdf document.
            var securitySetting = pdfDocument.SecuritySettings;

            // Set owner password from given parameter.
            securitySetting.OwnerPassword = defaultOwnerPassword;

            // Set user password from given parameter.
            securitySetting.UserPassword = password;

            // Disable printing with full quality.
            securitySetting.PermitFullQualityPrint = enablePrinting;

            // Disable printing.
            securitySetting.PermitPrint = enablePrinting;

            // Disable annotation.
            securitySetting.PermitAnnotations = enableEditing;

            // Disable assemble the document.
            securitySetting.PermitAssembleDocument = enableEditing;

            // Disable content extraction (copy paste text or save image).
            securitySetting.PermitExtractContent = enableEditing;

            // Disable content extraction for accessibility.
            //securitySetting.PermitAccessibilityExtractContent = enableEditing;

            // Disable forms fill.
            securitySetting.PermitFormsFill = enableEditing;

            // Disable modify the document.
            securitySetting.PermitModifyDocument = enableEditing;
        }
    }
}
