using System;
using Agit.Common.Attributes;

namespace TAMHR.ESS.Domain
{
    [DatabaseObject("SF_GET_HIRING_EMPLOYEE", DatabaseObjectType.TableValued)]
    public class HiringEmployeeStoredEntity
    {
        public Guid Id { get; set; }
        public string NoReg { get; set; }
        public string PlacementDate { get; set; }
        public string ActionType { get; set; }
        public string ReasonForAction { get; set; }
        public string Position { get; set; }
        public string PersonelArea { get; set; }
        public string EmployeeGroup { get; set; }
        public string EmployeeSubGroup { get; set; }
        public string SubArea { get; set; }
        public string WorkContract { get; set; }
        public string EffectiveDate { get; set; }
        public string SubClass { get; set; }
        public string LabourType { get; set; }
        public string Name { get; set; }
        public string FullName { get; set; }
        public string BirthPlace { get; set; }
        public string BirthDate { get; set; }
        public string Gender { get; set; }
        public string Religion { get; set; }
        public string BloodType { get; set; }
        public string Nationality { get; set; }
        public string NIK { get; set; }
        public string Passport { get; set; }
        public string KK { get; set; }
        public string BPJSNumber { get; set; }
        public string PhoneNumber { get; set; }
        public string email { get; set; }
        public string NPWP { get; set; }
        public string TaxStatus { get; set; }
        public string Dependence { get; set; }
        public string MaritalStatus { get; set; }
        public string MaritalNumber { get; set; }
        public string MaritalDate { get; set; }
        public string SimANumber { get; set; }
        public string SimCNumber { get; set; }
        public string PrimaryAddress { get; set; }
        public string PrimaryRT { get; set; }
        public string PrimaryRW { get; set; }
        public string PrimaryUrbanVillage { get; set; }
        public string PrimarySubDistrict { get; set; }
        public string PrimaryDistrict { get; set; }
        public string PrimaryProvince { get; set; }
        public string PrimaryPostalCode { get; set; }
        public string HomeAddress { get; set; }
        public string HomeRT { get; set; }
        public string HomeRW { get; set; }
        public string HomeUrbanVillage { get; set; }
        public string HomeSubDistrict { get; set; }
        public string HomeDistrict { get; set; }
        public string HomeProvince { get; set; }
        public string HomePostalCode { get; set; }
        public string BankAccountNumber { get; set; }
        public string BankAccountName { get; set; }
        public string BankAccountKey { get; set; }
        public string PaymentType { get; set; }
        public string AyahKandung { get; set; }
        public string AyahKandungBirthPlace { get; set; }
        public string AyahKandungBirthDate { get; set; }
        public string AyahKandungGender { get; set; }
        public string IbuKandung { get; set; }
        public string IbuKandungBirthPlace { get; set; }
        public string IbuKandungBirthDate { get; set; }
        public string IbuKandungGender { get; set; }
        public string SaudaraKandung { get; set; }
        public string SaudaraKandungBirthPlace { get; set; }
        public string SaudaraKandungBirthDate { get; set; }
        public string SaudaraKandungGender { get; set; }
        public string Pasangan { get; set; }
        public string PasanganBirthPlace { get; set; }
        public string PasanganBirthDate { get; set; }
        public string PasanganGender { get; set; }
        public string FirstChild { get; set; }
        public string FirstChildNumber { get; set; }
        public string FirstChildStatus { get; set; }
        public string FirstChildBirthPlace { get; set; }
        public string FirstChildBirthDate { get; set; }
        public string FirstChildGender { get; set; }
        public string SecondChild { get; set; }
        public string SecondChildNumber { get; set; }
        public string SecondChildStatus { get; set; }
        public string SecondChildBirthPlace { get; set; }
        public string SecondChildBirthDate { get; set; }
        public string SecondChildGender { get; set; }
        public string ThirdChild { get; set; }
        public string ThirdChildNumber { get; set; }
        public string ThirdChildStatus { get; set; }
        public string ThirdChildBirthPlace { get; set; }
        public string ThirdChildBirthDate { get; set; }
        public string ThirdChildGender { get; set; }
        public string AyahMertua { get; set; }
        public string AyahMertuaBirthPlace { get; set; }
        public string AyahMertuaBirthDate { get; set; }
        public string AyahMertuaGender { get; set; }
        public string IbuMertua { get; set; }
        public string IbuMertuaBirthPlace { get; set; }
        public string IbuMertuaBirthDate { get; set; }
        public string IbuMertuaGender { get; set; }
        public string KakekDariAyah { get; set; }
        public string KakekDariAyahBirthDate { get; set; }
        public string KakekDariAyahGender { get; set; }
        public string KakekDariIbu { get; set; }
        public string KakekDariIbuBirthDate { get; set; }
        public string KakekDariIbuGender { get; set; }
        public string NenekDariAyah { get; set; }
        public string NenekDariAyahBirthDate { get; set; }
        public string NenekDariAyahGender { get; set; }
        public string NenekDariIbu { get; set; }
        public string NenekDariIbuBirthDate { get; set; }
        public string NenekDariIbuGender { get; set; }
        public string EducationType { get; set; }
        public string Institute { get; set; }
        public string Major { get; set; }
        public string NationInstitute { get; set; }
        public string StartDateEducation { get; set; }
        public string GraduationDate { get; set; }
        public string FinalGrade { get; set; }
        public string Certificate { get; set; }
        public string JoinAstraDate { get; set; }
        public string WorkScheduleRule { get; set; }
        public string TimeManagementStatus { get; set; }
        public string TimeRecord { get; set; }
        public string IdVersion { get; set; }

    }
}
