using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Agit.Common;

namespace TAMHR.ESS.Domain
{
    [Table("TB_M_PERSONAL_DATA_MEDICAL_HISTORY")]
    public partial class PersonalDataMedicalHistory : IEntityBase<Guid>
    {
        [Key]
        public Guid Id { get; set; }
        public string NoReg { get; set; }
        public int? YearPeriod { get; set; }
        public int? GlukosaPuasa { get; set; }
        public int? SGOT { get; set; }
        public int? SGPT { get; set; }
        public string HBsAg { get; set; }
        public string AntiHBs { get; set; }
        public decimal? AsamUrat { get; set; }
        public int? KolesterolTotal { get; set; }
        public decimal? StatusBMI { get; set; }
        public string TekananDarah { get; set; }
        public decimal? Kreatinin { get; set; }
        public string HasilEKG { get; set; }
        public string HasilRontgen { get; set; }
        public string HealthEmployeeStatus { get; set; }
        public string CreatedBy { get; set; }
        public DateTime CreatedOn { get; set; }
        public string ModifiedBy { get; set; }
        public DateTime? ModifiedOn { get; set; }
        public bool RowStatus { get; set; }
        public string Paket { get; set; }
        public string LokasiMCU { get; set; }
        public int? Usia { get; set; }
        public string PenyakitPernahDiderita { get; set; }
        public string Perokok { get; set; }
        public int? JumlahBatangPerHari { get; set; }
        public string Miras { get; set; }
        public string Olahraga { get; set; }
        public int? FrequencyPerMinggu { get; set; }
        public string Kebisingan { get; set; }
        public string SuhuExtremePanasAtauDingin { get; set; }
        public string Radiasi { get; set; }
        public string GetaranLokal { get; set; }
        public string GetaranSeluruhTubuh { get; set; }
        public string LainnyaFisika { get; set; }
        public string Debu { get; set; }
        public string Asap { get; set; }
        public string LimbahB3 { get; set; }
        public string LainnyaKimia { get; set; }
        public string BakteriAtaVirusAtauJamurAtauParasit { get; set; }
        public string LainnyaBiologi { get; set; }
        public string GerakanBerulangDenganTangan { get; set; }
        public string AngkatBerat { get; set; }
        public string DudukLama { get; set; }
        public string BerdiriLama { get; set; }
        public string PosisiTubuhTidakErgonomis { get; set; }
        public string PencahayaanTidakSesuai { get; set; }
        public string BekerjaDepanLayar { get; set; }
        public string LainnyaErgonomis { get; set; }
        public string RiwayatHipertensi { get; set; }
        public string RiwayatDiabetes { get; set; }
        public string RiwayatPenyakitJantung { get; set; }
        public string RiwayatPenyakitGinjal { get; set; }
        public string RiwayatGangguanMental { get; set; }
        public string RiwayatPenyakitLain { get; set; }
        public string PenyakitSaatIni { get; set; }
        public string SedangBerobat { get; set; }
        public string ObatYangDiberikan { get; set; }
        public decimal? Tinggi { get; set; }
        public decimal? Berat { get; set; }
        public int? TekananDarahSistol { get; set; }
        public int? TekananDarahDiastol { get; set; }
        public string KesimpulanEKG { get; set; }
        public string KesimpulanTreadmill { get; set; }
        public string KesanPhotoRontgen { get; set; }
        public string KesimpulanUsgAbdomen { get; set; }
        public string HasilUsgMammae { get; set; }
        public string KesimpulanUsgMammae { get; set; }
        public string KesimpulanFisik { get; set; }
        public string KesimpulanButaWarna { get; set; }
        public string KesimpulanPemVisusMata { get; set; }
        public string HasilPapsmear { get; set; }
        public string KesimpulanPamsmear { get; set; }
        public decimal? Hemoglobine { get; set; }
        public int? Hematocrit { get; set; }
        public int? Leucocyte { get; set; }
        public decimal? TotalPlatelets { get; set; }
        public decimal? Eryrocyte { get; set; }
        public decimal? MCV { get; set; }
        public int? MCH { get; set; }
        public int? MCHC { get; set; }
        public int? ESR { get; set; }
        public decimal? HbA1c { get; set; }
        public int? GammaGT { get; set; }
        public int? Ureum { get; set; }
        public decimal? GFR { get; set; }
        public int? HDL { get; set; }
        public int? LDL { get; set; }
        public int? Triglyceride { get; set; }
        public string PlateletAggregation { get; set; }
        public int? Fibrinogen { get; set; }
        public decimal? CEA { get; set; }
        public string PSA { get; set; }
        public int? Ca125 { get; set; }
        public decimal? VitD25OH { get; set; }
        public string UrinDarah { get; set; }
        public string UrinBakteri { get; set; }
        public string UrinKristal { get; set; }
        public string UrinLeukosit { get; set; }
        public int? ScoreAmbiguity { get; set; }
        public string KesimpulanAmbiguity { get; set; }
        public int? ScoreConflict { get; set; }
        public string KesimpulanConflict { get; set; }
        public int? ScoreQuantitative { get; set; }
        public string KesimpulanQuantitative { get; set; }
        public int? ScoreQualitative { get; set; }
        public string KesimpulanQualitative { get; set; }
        public int? ScoreCareerDevelopment { get; set; }
        public string KesimpulanCareerDevelopment { get; set; }
        public int? ScoreResponsibilityforPeople { get; set; }
        public string KesimpulanResponsibilityforPeople { get; set; }
        public string KesimpulanLab { get; set; }
        public string Saran { get; set; }

        [NotMapped]
        public string NoregMcu { get; set; }

    }

    [Table("VW_MCU_DETAIL")]
    public partial class McuView : IEntityMarker
    {
        //[Key]
        public Guid Id { get; set; }
        public string NoReg { get; set; }
        public int? YearPeriod { get; set; }
        public int? GlukosaPuasa { get; set; }
        public int? SGOT { get; set; }
        public int? SGPT { get; set; }
        public string HBsAg { get; set; }
        public string AntiHBs { get; set; }
        public decimal? AsamUrat { get; set; }
        public int? KolesterolTotal { get; set; }
        public decimal? StatusBMI { get; set; }
        public string TekananDarah { get; set; }
        public decimal? Kreatinin { get; set; }
        public string HasilEKG { get; set; }
        public string HasilRontgen { get; set; }
        public string HealthEmployeeStatus { get; set; }
        public string CreatedBy { get; set; }
        public DateTime CreatedOn { get; set; }
        public string ModifiedBy { get; set; }
        public DateTime? ModifiedOn { get; set; }
        public bool RowStatus { get; set; }
        public string Paket { get; set; }
        public string LokasiMCU { get; set; }
        public int? Usia { get; set; }
        public string PenyakitPernahDiderita { get; set; }
        public string Perokok { get; set; }
        public int? JumlahBatangPerHari { get; set; }
        public string Miras { get; set; }
        public string Olahraga { get; set; }
        public int? FrequencyPerMinggu { get; set; }
        public string Kebisingan { get; set; }
        public string SuhuExtremePanasAtauDingin { get; set; }
        public string Radiasi { get; set; }
        public string GetaranLokal { get; set; }
        public string GetaranSeluruhTubuh { get; set; }
        public string LainnyaFisika { get; set; }
        public string Debu { get; set; }
        public string Asap { get; set; }
        public string LimbahB3 { get; set; }
        public string LainnyaKimia { get; set; }
        public string BakteriAtaVirusAtauJamurAtauParasit { get; set; }
        public string LainnyaBiologi { get; set; }
        public string GerakanBerulangDenganTangan { get; set; }
        public string AngkatBerat { get; set; }
        public string DudukLama { get; set; }
        public string BerdiriLama { get; set; }
        public string PosisiTubuhTidakErgonomis { get; set; }
        public string PencahayaanTidakSesuai { get; set; }
        public string BekerjaDepanLayar { get; set; }
        public string LainnyaErgonomis { get; set; }
        public string RiwayatHipertensi { get; set; }
        public string RiwayatDiabetes { get; set; }
        public string RiwayatPenyakitJantung { get; set; }
        public string RiwayatPenyakitGinjal { get; set; }
        public string RiwayatGangguanMental { get; set; }
        public string RiwayatPenyakitLain { get; set; }
        public string PenyakitSaatIni { get; set; }
        public string SedangBerobat { get; set; }
        public string ObatYangDiberikan { get; set; }
        public decimal? Tinggi { get; set; }
        public decimal? Berat { get; set; }
        public int? TekananDarahSistol { get; set; }
        public int? TekananDarahDiastol { get; set; }
        public string KesimpulanEKG { get; set; }
        public string KesimpulanTreadmill { get; set; }
        public string KesanPhotoRontgen { get; set; }
        public string KesimpulanUsgAbdomen { get; set; }
        public string HasilUsgMammae { get; set; }
        public string KesimpulanUsgMammae { get; set; }
        public string KesimpulanFisik { get; set; }
        public string KesimpulanButaWarna { get; set; }
        public string KesimpulanPemVisusMata { get; set; }
        public string HasilPapsmear { get; set; }
        public string KesimpulanPamsmear { get; set; }
        public decimal? Hemoglobine { get; set; }
        public int? Hematocrit { get; set; }
        public int? Leucocyte { get; set; }
        public decimal? TotalPlatelets { get; set; }
        public decimal? Eryrocyte { get; set; }
        public decimal? MCV { get; set; }
        public int? MCH { get; set; }
        public int? MCHC { get; set; }
        public int? ESR { get; set; }
        public decimal? HbA1c { get; set; }
        public int? GammaGT { get; set; }
        public int? Ureum { get; set; }
        public decimal? GFR { get; set; }
        public int? HDL { get; set; }
        public int? LDL { get; set; }
        public int? Triglyceride { get; set; }
        public string PlateletAggregation { get; set; }
        public int? Fibrinogen { get; set; }
        public decimal? CEA { get; set; }
        public string PSA { get; set; }
        public int? Ca125 { get; set; }
        public decimal? VitD25OH { get; set; }
        public string UrinDarah { get; set; }
        public string UrinBakteri { get; set; }
        public string UrinKristal { get; set; }
        public string UrinLeukosit { get; set; }
        public int? ScoreAmbiguity { get; set; }
        public string KesimpulanAmbiguity { get; set; }
        public int? ScoreConflict { get; set; }
        public string KesimpulanConflict { get; set; }
        public int? ScoreQuantitative { get; set; }
        public string KesimpulanQuantitative { get; set; }
        public int? ScoreQualitative { get; set; }
        public string KesimpulanQualitative { get; set; }
        public int? ScoreCareerDevelopment { get; set; }
        public string KesimpulanCareerDevelopment { get; set; }
        public int? ScoreResponsibilityforPeople { get; set; }
        public string KesimpulanResponsibilityforPeople { get; set; }
        public string KesimpulanLab { get; set; }
        public string Saran { get; set; }

    }
}
